//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Books")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILibrayService")]
    public interface ILibrayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrayService/AddBook", ReplyAction="http://tempuri.org/ILibrayService/AddBookResponse")]
        void AddBook(Client.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrayService/AddBook", ReplyAction="http://tempuri.org/ILibrayService/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(Client.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrayService/UpdateBookPrice", ReplyAction="http://tempuri.org/ILibrayService/UpdateBookPriceResponse")]
        void UpdateBookPrice(Client.ServiceReference1.Book book, int Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrayService/UpdateBookPrice", ReplyAction="http://tempuri.org/ILibrayService/UpdateBookPriceResponse")]
        System.Threading.Tasks.Task UpdateBookPriceAsync(Client.ServiceReference1.Book book, int Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrayService/PrintAllBooks", ReplyAction="http://tempuri.org/ILibrayService/PrintAllBooksResponse")]
        void PrintAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibrayService/PrintAllBooks", ReplyAction="http://tempuri.org/ILibrayService/PrintAllBooksResponse")]
        System.Threading.Tasks.Task PrintAllBooksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibrayServiceChannel : Client.ServiceReference1.ILibrayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibrayServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ILibrayService>, Client.ServiceReference1.ILibrayService {
        
        public LibrayServiceClient() {
        }
        
        public LibrayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibrayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibrayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBook(Client.ServiceReference1.Book book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(Client.ServiceReference1.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public void UpdateBookPrice(Client.ServiceReference1.Book book, int Price) {
            base.Channel.UpdateBookPrice(book, Price);
        }
        
        public System.Threading.Tasks.Task UpdateBookPriceAsync(Client.ServiceReference1.Book book, int Price) {
            return base.Channel.UpdateBookPriceAsync(book, Price);
        }
        
        public void PrintAllBooks() {
            base.Channel.PrintAllBooks();
        }
        
        public System.Threading.Tasks.Task PrintAllBooksAsync() {
            return base.Channel.PrintAllBooksAsync();
        }
    }
}
